version: "3.8"

services:
  aod_clock_api: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aod_clock_api
    ports:
      - "8080:8080"
    restart: unless-stopped
    command: >
      sh -c "echo 'Files in container:' && ls -la && uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - aod_network

  aod_cloudflare_tunnel:
    image: cloudflare/cloudflared:latest
    container_name: aod_cloudflare_tunnel
    command: tunnel --no-autoupdate run --protocol h2mux --proxy-port 8080 --token eyJhIjoiYzliNzkzYjZhMGFiNzcxMGRlMWZjZGI5NTE2ZTQ5NWYiLCJ0IjoiY2E5YmJmOTItNDBhOC00Zjc2LWJmOTgtZGM0NzA1ZWU1NGZiIiwicyI6IlpqUTVORGcxTVdJdFpqa3lPQzAwT1RBNUxUa3dabUl0Tm1SaFpUZzROMlJpWXpKaSJ9
    restart: unless-stopped
    depends_on:
      - aod_clock_api
    networks:
      - aod_network

networks:
   aod_network:
    driver: bridge
